<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;

class RolePermissionSeeder extends Seeder
{
    public function run()
    {
        // Reset cached roles and permissions
        app()[\Spatie\Permission\PermissionRegistrar::class]->forgetCachedPermissions();

        // Create permissions
        $permissions = [
            /*
            |--------------------------------------------------------------------------
            | Dashboard & Common
            |--------------------------------------------------------------------------
            */
            'dashboard.main.view',

            'student.list.view',

            'attendance.list.view',
            'attendance.manage.update',

            'exam.result.view',
            'exam.term_test.manage',

            'resource.list.view',
            'resource.manage.update',
            'resource.allocation.create',
            'resource.allocation.view',

            /*
            |--------------------------------------------------------------------------
            | My Profile Management
            |--------------------------------------------------------------------------
            */

            // My Profile – View
            'my-profile.general.view',
            'my-profile.qualification.view',
            'my-profile.employment.view',
            'my-profile.family.view',
            'my-profile.pension-and-payment.view',
            'my-profile.edit-request.view',

            // My Profile – Management
            'my-profile.edit-request.create',
            'my-profile.edit-request.response',
            'my-profile.verify',
            'my-profile.confirm',
            'my-profile.pdf.view',

            // My Profile – Actions
            'my-profile.personal-cultural.update',
            'my-profile.health.update',
            'my-profile.contact-information.update',
            'my-profile.location-information.update',
            'my-profile.temporary-location-information.update',

            'my-profile.qualification.create',
            'my-profile.qualification.delete',

            'my-profile.employment.current-appointment.update',
            'my-profile.employment.first-appointment.update',
            'my-profile.employment.sltes-information.update',
            'my-profile.employment.previous-service.create',
            'my-profile.employment.previous-service.delete',
            'my-profile.employment.working-place-history.create',
            'my-profile.employment.working-place-history.delete',
            'my-profile.employment.position-history.create',
            'my-profile.employment.position-history.delete',

            'my-profile.pension-and-payment.update',

            'my-profile.family.create',
            'my-profile.family.delete',



            /*
            |--------------------------------------------------------------------------
            | Teacher Management
            |--------------------------------------------------------------------------
            */
            'teacher.list.view',
            'teacher.create',
            'teacher.update',
            'teacher.delete',

            // Teacher Profile – View
            'teacher.profile.general.view',
            'teacher.profile.qualification.view',
            'teacher.profile.employment.view',
            'teacher.profile.family.view',
            'teacher.profile.pension-and-payment.view',
            'teacher.profile.edit-request.view',

            // Teacher Profile – Management
            'teacher.profile.edit-request.create',
            'teacher.profile.edit-request.response',
            'teacher.profile.verify',
            'teacher.profile.confirm',
            'teacher.profile.id.view',
            'teacher.profile.pdf.view',

            // Teacher Profile – Actions
            'teacher.bulk.upload',

            'teacher.profile.personal-cultural.update',
            'teacher.profile.health.update',
            'teacher.profile.contact-information.update',
            'teacher.profile.location-information.update',
            'teacher.profile.temporary-location-information.update',

            'teacher.profile.qualification.create',
            'teacher.profile.qualification.delete',

            'teacher.profile.employment.current-appointment.update',
            'teacher.profile.employment.first-appointment.update',
            'teacher.profile.employment.teacher-information.update',
            'teacher.profile.employment.previous-service.create',
            'teacher.profile.employment.previous-service.delete',
            'teacher.profile.employment.working-place-history.create',
            'teacher.profile.employment.working-place-history.delete',
            'teacher.profile.employment.position-history.create',
            'teacher.profile.employment.position-history.delete',

            'teacher.profile.pension-and-payment.update',

            'teacher.profile.family.create',
            'teacher.profile.family.delete',

            'teacher.promotion.demote',
            'teacher.promotion.promote',
            'teacher.promotion.view',

            'teacher.overview.view',
            'teacher.leave-operations.view',
            'teacher.attachments.view',
            'teacher.pension-system.view',
            'teacher.specializations.view',
            'teacher.benefits-and-health.view',


            /*
            |--------------------------------------------------------------------------
            | Principal Management
            |--------------------------------------------------------------------------
            */
            'principal.list.view',
            'principal.create',
            'principal.update',
            'principal.delete',

            // Principal Profile – View
            'principal.profile.general.view',
            'principal.profile.qualification.view',
            'principal.profile.employment.view',
            'principal.profile.family.view',
            'principal.profile.pension-and-payment.view',
            'principal.profile.edit-request.view',

            // Principal Profile – Management
            'principal.profile.edit-request.create',
            'principal.profile.edit-request.response',
            'principal.profile.verify',
            'principal.profile.confirm',
            'principal.profile.id.view',
            'principal.profile.pdf.view',

            // Principal Profile – Actions
            'principal.bulk.upload',

            'principal.profile.personal-cultural.update',
            'principal.profile.health.update',
            'principal.profile.contact-information.update',
            'principal.profile.location-information.update',
            'principal.profile.temporary-location-information.update',

            'principal.profile.qualification.create',
            'principal.profile.qualification.delete',

            'principal.profile.employment.current-appointment.update',
            'principal.profile.employment.first-appointment.update',
            'principal.profile.employment.principal-information.update',
            'principal.profile.employment.previous-service.create',
            'principal.profile.employment.previous-service.delete',

            'principal.profile.employment.working-place-history.create',
            'principal.profile.employment.working-place-history.delete',
            'principal.profile.employment.position-history.create',
            'principal.profile.employment.position-history.delete',

            'principal.profile.pension-and-payment.update',

            'principal.profile.family.create',
            'principal.profile.family.delete',


            /*
            |--------------------------------------------------------------------------
            | DOS Management
            |--------------------------------------------------------------------------
            */
            'dos.list.view',
            'dos.create',
            'dos.update',
            'dos.delete',

            // DOS Profile – View
            'dos.profile.general.view',
            'dos.profile.qualification.view',
            'dos.profile.employment.view',
            'dos.profile.family.view',
            'dos.profile.pension-and-payment.view',
            'dos.profile.edit-request.view',

            // DOS Profile – Management
            'dos.profile.edit-request.create',
            'dos.profile.edit-request.response',
            'dos.profile.verify',
            'dos.profile.confirm',
            'dos.profile.id.view',
            'dos.profile.pdf.view',

            // DOS Profile – Actions
            'dos.bulk.upload',

            'dos.profile.personal-cultural.update',
            'dos.profile.health.update',
            'dos.profile.contact-information.update',
            'dos.profile.location-information.update',
            'dos.profile.temporary-location-information.update',

            'dos.profile.qualification.create',
            'dos.profile.qualification.delete',

            'dos.profile.employment.current-appointment.update',
            'dos.profile.employment.first-appointment.update',
            'dos.profile.employment.dos-information.update',
            'dos.profile.employment.previous-service.create',
            'dos.profile.employment.previous-service.delete',

            'dos.profile.employment.working-place-history.create',
            'dos.profile.employment.working-place-history.delete',
            'dos.profile.employment.position-history.create',
            'dos.profile.employment.position-history.delete',

            'dos.profile.pension-and-payment.update',

            'dos.profile.family.create',
            'dos.profile.family.delete',


            /*
            |--------------------------------------------------------------------------
            | MSO Management
            |--------------------------------------------------------------------------
            */
            'mso.list.view',
            'mso.create',
            'mso.update',
            'mso.delete',

            // MSO Profile – View
            'mso.profile.general.view',
            'mso.profile.qualification.view',
            'mso.profile.employment.view',
            'mso.profile.family.view',
            'mso.profile.pension-and-payment.view',
            'mso.profile.edit-request.view',

            // MSO Profile – Management
            'mso.profile.edit-request.create',
            'mso.profile.edit-request.response',
            'mso.profile.verify',
            'mso.profile.confirm',
            'mso.profile.id.view',
            'mso.profile.pdf.view',

            // MSO Profile – Actions
            'mso.bulk.upload',

            'mso.profile.personal-cultural.update',
            'mso.profile.health.update',
            'mso.profile.contact-information.update',
            'mso.profile.location-information.update',
            'mso.profile.temporary-location-information.update',

            'mso.profile.qualification.create',
            'mso.profile.qualification.delete',

            'mso.profile.employment.current-appointment.update',
            'mso.profile.employment.first-appointment.update',
            'mso.profile.employment.mso-information.update',
            'mso.profile.employment.previous-service.create',
            'mso.profile.employment.previous-service.delete',

            'mso.profile.employment.working-place-history.create',
            'mso.profile.employment.working-place-history.delete',
            'mso.profile.employment.position-history.create',
            'mso.profile.employment.position-history.delete',

            'mso.profile.pension-and-payment.update',

            'mso.profile.family.create',
            'mso.profile.family.delete',


            /*
            |--------------------------------------------------------------------------
            | SLEAS Management
            |--------------------------------------------------------------------------
            */
            'sleas.list.view',
            'sleas.create',
            'sleas.update',
            'sleas.delete',

            // SLEAS Profile – View
            'sleas.profile.general.view',
            'sleas.profile.qualification.view',
            'sleas.profile.employment.view',
            'sleas.profile.family.view',
            'sleas.profile.pension-and-payment.view',
            'sleas.profile.edit-request.view',

            // SLEAS Profile – Management
            'sleas.profile.edit-request.create',
            'sleas.profile.edit-request.response',
            'sleas.profile.verify',
            'sleas.profile.confirm',
            'sleas.profile.id.view',
            'sleas.profile.pdf.view',

            // SLEAS Profile – Actions
            'sleas.bulk.upload',

            'sleas.profile.personal-cultural.update',
            'sleas.profile.health.update',
            'sleas.profile.contact-information.update',
            'sleas.profile.location-information.update',
            'sleas.profile.temporary-location-information.update',

            'sleas.profile.qualification.create',
            'sleas.profile.qualification.delete',

            'sleas.profile.employment.current-appointment.update',
            'sleas.profile.employment.first-appointment.update',
            'sleas.profile.employment.sleas-information.update',
            'sleas.profile.employment.previous-service.create',
            'sleas.profile.employment.previous-service.delete',

            'sleas.profile.employment.working-place-history.create',
            'sleas.profile.employment.working-place-history.delete',
            'sleas.profile.employment.position-history.create',
            'sleas.profile.employment.position-history.delete',

            'sleas.profile.pension-and-payment.update',

            'sleas.profile.family.create',
            'sleas.profile.family.delete',

            /*
            |--------------------------------------------------------------------------
            | SLTAS Management
            |--------------------------------------------------------------------------
            */
            'sltas.list.view',
            'sltas.create',
            'sltas.update',
            'sltas.delete',

            // SLTAS Profile – View
            'sltas.profile.general.view',
            'sltas.profile.qualification.view',
            'sltas.profile.employment.view',
            'sltas.profile.family.view',
            'sltas.profile.pension-and-payment.view',
            'sltas.profile.edit-request.view',

            // SLTAS Profile – Management
            'sltas.profile.edit-request.create',
            'sltas.profile.edit-request.response',
            'sltas.profile.verify',
            'sltas.profile.confirm',
            'sltas.profile.id.view',
            'sltas.profile.pdf.view',

            // SLTAS Profile – Actions
            'sltas.bulk.upload',

            'sltas.profile.personal-cultural.update',
            'sltas.profile.health.update',
            'sltas.profile.contact-information.update',
            'sltas.profile.location-information.update',
            'sltas.profile.temporary-location-information.update',

            'sltas.profile.qualification.create',
            'sltas.profile.qualification.delete',

            'sltas.profile.employment.current-appointment.update',
            'sltas.profile.employment.first-appointment.update',
            'sltas.profile.employment.sltas-information.update',
            'sltas.profile.employment.previous-service.create',
            'sltas.profile.employment.previous-service.delete',

            'sltas.profile.employment.working-place-history.create',
            'sltas.profile.employment.working-place-history.delete',
            'sltas.profile.employment.position-history.create',
            'sltas.profile.employment.position-history.delete',

            'sltas.profile.pension-and-payment.update',

            'sltas.profile.family.create',
            'sltas.profile.family.delete',

            /*
            |--------------------------------------------------------------------------
            | SLTES Management
            |--------------------------------------------------------------------------
            */
            'sltes.list.view',
            'sltes.create',
            'sltes.update',
            'sltes.delete',

            // SLTES Profile – View
            'sltes.profile.general.view',
            'sltes.profile.qualification.view',
            'sltes.profile.employment.view',
            'sltes.profile.family.view',
            'sltes.profile.pension-and-payment.view',
            'sltes.profile.edit-request.view',

            // SLTES Profile – Management
            'sltes.profile.edit-request.create',
            'sltes.profile.edit-request.response',
            'sltes.profile.verify',
            'sltes.profile.confirm',
            'sltes.profile.id.view',
            'sltes.profile.pdf.view',

            // SLTES Profile – Actions
            'sltes.bulk.upload',

            'sltes.profile.personal-cultural.update',
            'sltes.profile.health.update',
            'sltes.profile.contact-information.update',
            'sltes.profile.location-information.update',
            'sltes.profile.temporary-location-information.update',

            'sltes.profile.qualification.create',
            'sltes.profile.qualification.delete',

            'sltes.profile.employment.current-appointment.update',
            'sltes.profile.employment.first-appointment.update',
            'sltes.profile.employment.sltes-information.update',
            'sltes.profile.employment.previous-service.create',
            'sltes.profile.employment.previous-service.delete',

            'sltes.profile.employment.working-place-history.create',
            'sltes.profile.employment.working-place-history.delete',
            'sltes.profile.employment.position-history.create',
            'sltes.profile.employment.position-history.delete',

            'sltes.profile.pension-and-payment.update',

            'sltes.profile.family.create',
            'sltes.profile.family.delete',

            /*
            |--------------------------------------------------------------------------
            | SLAS Management
            |--------------------------------------------------------------------------
            */
            'slas.list.view',
            'slas.create',
            'slas.update',
            'slas.delete',

            // SLAS Profile – View
            'slas.profile.general.view',
            'slas.profile.qualification.view',
            'slas.profile.employment.view',
            'slas.profile.family.view',
            'slas.profile.pension-and-payment.view',
            'slas.profile.edit-request.view',

            // SLAS Profile – Management
            'slas.profile.edit-request.create',
            'slas.profile.edit-request.response',
            'slas.profile.verify',
            'slas.profile.confirm',
            'slas.profile.id.view',
            'slas.profile.pdf.view',

            // SLAS Profile – Actions
            'slas.bulk.upload',

            'slas.profile.personal-cultural.update',
            'slas.profile.health.update',
            'slas.profile.contact-information.update',
            'slas.profile.location-information.update',
            'slas.profile.temporary-location-information.update',

            'slas.profile.qualification.create',
            'slas.profile.qualification.delete',

            'slas.profile.employment.current-appointment.update',
            'slas.profile.employment.first-appointment.update',
            'slas.profile.employment.slas-information.update',
            'slas.profile.employment.previous-service.create',
            'slas.profile.employment.previous-service.delete',

            'slas.profile.employment.working-place-history.create',
            'slas.profile.employment.working-place-history.delete',
            'slas.profile.employment.position-history.create',
            'slas.profile.employment.position-history.delete',

            'slas.profile.pension-and-payment.update',

            'slas.profile.family.create',
            'slas.profile.family.delete',


            /*
            |--------------------------------------------------------------------------
            | SLAcS Management
            |--------------------------------------------------------------------------
            */
            'slacs.list.view',
            'slacs.create',
            'slacs.update',
            'slacs.delete',

            // SLAcS Profile – View
            'slacs.profile.general.view',
            'slacs.profile.qualification.view',
            'slacs.profile.employment.view',
            'slacs.profile.family.view',
            'slacs.profile.pension-and-payment.view',
            'slacs.profile.edit-request.view',

            // SLAcS Profile – Management
            'slacs.profile.edit-request.create',
            'slacs.profile.edit-request.response',
            'slacs.profile.verify',
            'slacs.profile.confirm',
            'slacs.profile.id.view',
            'slacs.profile.pdf.view',

            // SLAcS Profile – Actions
            'slacs.bulk.upload',

            'slacs.profile.personal-cultural.update',
            'slacs.profile.health.update',
            'slacs.profile.contact-information.update',
            'slacs.profile.location-information.update',
            'slacs.profile.temporary-location-information.update',

            'slacs.profile.qualification.create',
            'slacs.profile.qualification.delete',

            'slacs.profile.employment.current-appointment.update',
            'slacs.profile.employment.first-appointment.update',
            'slacs.profile.employment.slacs-information.update',
            'slacs.profile.employment.previous-service.create',
            'slacs.profile.employment.previous-service.delete',

            'slacs.profile.employment.working-place-history.create',
            'slacs.profile.employment.working-place-history.delete',
            'slacs.profile.employment.position-history.create',
            'slacs.profile.employment.position-history.delete',

            'slacs.profile.pension-and-payment.update',

            'slacs.profile.family.create',
            'slacs.profile.family.delete',

            /*
            |--------------------------------------------------------------------------
            | Employee Management
            |--------------------------------------------------------------------------
            */
            'employee.profile.create.any',


            /*
            |--------------------------------------------------------------------------
            | User Management
            |--------------------------------------------------------------------------
            */
            'user.list.view',
            'user.create',
            'user.update',
            'user.password.reset',
            'user.status.update',
            'user.delete',
            'user.edit',


            /*
            |--------------------------------------------------------------------------
            | Institution Management
            |--------------------------------------------------------------------------
            */
            'institution.list.view',
            'institution.create',
            'institution.update',

            'institution.profile.view',
            'institution.profile.overview.view',
            'institution.profile.profile.view',
            'institution.profile.staff.view',
            'institution.profile.report-module.view',
            'institution.profile.report-module.pdf',
            'institution.profile.report-module.xls',

            'institution.basic_information.update',
            'institution.contact_details.update',
            'institution.location_administration.update',
            'institution.mission_vision.update',
            'institution.student_enrollment.update',


            /*
            |--------------------------------------------------------------------------
            | Appointment Subject Management
            |--------------------------------------------------------------------------
            */
            'appointment_subject.list.view',
            'appointment_subject.create',
            'appointment_subject.update',
            'appointment_subject.delete',
            'appointment_subject.view',


            /*
            |--------------------------------------------------------------------------
            | Teaching Subject Management
            |--------------------------------------------------------------------------
            */
            'teaching_subject.list.view',
            'teaching_subject.create',
            'teaching_subject.update',
            'teaching_subject.delete',
            'teaching_subject.view',


            /*
            |--------------------------------------------------------------------------
            | Office Management (MOE / PMOE / PEO / ZEO / DEO)
            |--------------------------------------------------------------------------
            */
            // Lists
            'office.overview',
            'office.moe.list.view',
            'office.pmoe.list.view',
            'office.peo.list.view',
            'office.zeo.list.view',
            'office.deo.list.view',
            'office.institution.list.view',

            // Create
            'office.moe.create',
            'office.pmoe.create',
            'office.peo.create',
            'office.zeo.create',
            'office.deo.create',
            'office.institution.create',

            // Profile
            'office.moe.profile.overview.view',
            'office.pmoe.profile.overview.view',
            'office.peo.profile.overview.view',
            'office.zeo.profile.overview.view',
            'office.deo.profile.overview.view',

            // Update
            'office.moe.update',
            'office.pmoe.update',
            'office.peo.update',
            'office.zeo.update',
            'office.deo.update',
            'office.institution.update',

            // Delete
            'office.moe.delete',
            'office.pmoe.delete',
            'office.peo.delete',
            'office.zeo.delete',
            'office.deo.delete',
            'office.institution.delete',

            // Office Profiles - MOE
            'office.moe.profile.profile.view',
            'office.moe.profile.staff.view',
            'office.moe.profile.dms-cadre-summary.view',

            // Office Profiles - PMOE
            'office.pmoe.profile.profile.view',
            'office.pmoe.profile.staff.view',
            'office.pmoe.profile.dms-cadre-summary.view',

            // Office Profiles - PEO
            'office.peo.profile.profile.view',
            'office.peo.profile.staff.view',
            'office.peo.profile.zeo-list.view',
            'office.peo.profile.dms-cadre-summary.view',

            // Office Profiles - ZEO
            'office.zeo.profile.profile.view',
            'office.zeo.profile.staff.view',
            'office.zeo.profile.institutions-list.view',
            'office.zeo.profile.institution-groups.view',
            'office.zeo.profile.institution-groups.create',
            'office.zeo.profile.institution-groups.update',
            'office.zeo.profile.teachers-list.view',
            'office.zeo.profile.principals-list.view',
            'office.zeo.profile.report-module.view',
            'office.zeo.profile.dms-cadre-summary.view',

            // Office Profiles - DEO
            'office.deo.profile.profile.view',
            'office.deo.profile.staff.view',
            'office.deo.profile.report-module.view',
            'office.deo.profile.dms-cadre-summary.view',

            'office.hierarchy.view',

            // institution profile
            'office.institution.profile.overview.view',
            'office.institution.profile.profile.view',
            'office.institution.profile.staff.view',
            'office.institution.profile.report-module.view',
            'office.institution.profile.report-module.pdf',
            'office.institution.profile.report-module.xls',

            // Cadre DMS Approved
            'cadre-dms-approved.index.view',
            'cadre-dms-approved.add',
            'cadre-dms-approved.institution.view',
            'cadre-dms-approved.edit',

            'institution.profile.cadre-dms-approved.view',
            'office.institution.profile.cadre-dms-approved.view',

            'alerts.overview.view',

            /*
            |--------------------------------------------------------------------------
            | Transfer Management
            |--------------------------------------------------------------------------
            */
            'transfer.portal.view',
            'transfer.policy.view',
            'transfer.policy.manage',
            'transfer.request.view',
            'transfer.board.view',
            'transfer.institution-request.view',
            'transfer.zeo-request.view',
            'transfer.annual.view',
            'transfer.mutual.view',
            'transfer.special.view',

            /*
            |--------------------------------------------------------------------------
            | National School Management
            |--------------------------------------------------------------------------
            */
            'national-school.overview.view',
            'national-school.list.view',
            'national-school.teacher-list.view',
            'national-school.principal-list.view',
            'national-school.sleas-list.view',
            'national-school.dms-approved-cadre.view',

            /*
            |--------------------------------------------------------------------------
            | Employee Management
            |--------------------------------------------------------------------------
            */
            'employee.overview.view',
            'employee.promotion.manage',
            'employee.termination.manage',
            'employee.mytransfer',
            'employee.changing-workplace.manage',

            /*
            |--------------------------------------------------------------------------
            | Institution Group Management
            |--------------------------------------------------------------------------
            */
            'institution-group.index.view',
            'institution-group.institution-list.view',
            'institution-group.principal-list.view',
            'institution-group.teacher-list.view',
        ];


        foreach ($permissions as $permission) {
            Permission::firstOrCreate(['name' => $permission]);
        }

        $selfProfilePermissions = [
            'my-profile.general.view',
            'my-profile.qualification.view',
            'my-profile.employment.view',
            'my-profile.family.view',
            'my-profile.pension-and-payment.view',
            'my-profile.edit-request.view',
            'my-profile.edit-request.create',
            'my-profile.pdf.view',
        ];

        // Create super admin role and assign specific permissions
        $superAdminRole = Role::firstOrCreate(['name' => 'super admin']);
        $superAdminRole->syncPermissions(Permission::all());

        // Create teacher role and assign specific permissions
        $teacherRole = Role::firstOrCreate(['name' => 'teacher']);
        $teacherRole->syncPermissions([
            'dashboard.main.view',
            'student.list.view',
            'attendance.list.view',
            'attendance.manage.update',
            'exam.result.view',
            'exam.term_test.manage',
            'resource.list.view',
            'resource.manage.update',
            'resource.allocation.create',
            'resource.allocation.view',
            'my-profile.general.view',
            'my-profile.qualification.view',
            'my-profile.employment.view',
            'my-profile.family.view',
            'my-profile.pension-and-payment.view',
            'my-profile.edit-request.view',
            'my-profile.edit-request.create',
            'my-profile.pdf.view',
            'institution.list.view',
            'institution.profile.view',
            'transfer.policy.view',
            'employee.mytransfer',
            'transfer.annual.view',
            'transfer.mutual.view',
            'transfer.special.view',
        ]);

        // Create principal role and assign specific permissions
        $principalRole = Role::firstOrCreate(['name' => 'principal']);
        $principalRole->syncPermissions([
            'dashboard.main.view',
            'student.list.view',
            'attendance.list.view',
            'attendance.manage.update',
            'exam.result.view',
            'exam.term_test.manage',
            'resource.list.view',
            'resource.manage.update',
            'resource.allocation.create',
            'resource.allocation.view',
            'my-profile.general.view',
            'my-profile.qualification.view',
            'my-profile.employment.view',
            'my-profile.family.view',
            'my-profile.pension-and-payment.view',
            'my-profile.edit-request.view',
            'my-profile.edit-request.create',
            'my-profile.pdf.view',
            'user.list.view',
            'user.password.reset',
            'institution.list.view',
            'institution.profile.view',
            'institution.profile.overview.view',
            'institution.profile.staff.view',
            'institution.profile.report-module.view',
            'institution.profile.report-module.pdf',
            'office.institution.list.view',
            'office.institution.profile.overview.view',
            'office.institution.profile.profile.view',
            'office.institution.profile.staff.view',
            'office.institution.profile.report-module.view',
            'office.institution.profile.report-module.pdf',
            'office.institution.profile.report-module.xls',
            'office.institution.profile.cadre-dms-approved.view',
            'institution.profile.profile.view',
            'office.hierarchy.view',
            'transfer.institution-request.view',
            'employee.overview.view',
            'office.overview',
            'employee.mytransfer',
        ]);

        // Create Zonal Data Entry role and assign specific permissions
        $zonalDataEntryRole = Role::firstOrCreate(['name' => 'Zonal Data Entry']);
        $zonalDataEntryRole->syncPermissions([
            'my-profile.general.view',
            'my-profile.qualification.view',
            'my-profile.employment.view',
            'my-profile.family.view',
            'my-profile.pension-and-payment.view',
            'my-profile.edit-request.view',
            'my-profile.pdf.view',
            'teacher.list.view',
            'teacher.create',
            'teacher.profile.general.view',
            'teacher.profile.qualification.view',
            'teacher.profile.employment.view',
            'teacher.profile.family.view',
            'teacher.profile.pension-and-payment.view',
            'teacher.profile.edit-request.view',
            'teacher.profile.edit-request.response',
            'teacher.profile.pdf.view',
            'teacher.profile.personal-cultural.update',
            'teacher.profile.health.update',
            'teacher.profile.contact-information.update',
            'teacher.profile.location-information.update',
            'teacher.profile.temporary-location-information.update',
            'teacher.profile.qualification.create',
            'teacher.profile.qualification.delete',
            'teacher.profile.employment.current-appointment.update',
            'teacher.profile.employment.first-appointment.update',
            'teacher.profile.employment.teacher-information.update',
            'teacher.profile.employment.previous-service.create',
            'teacher.profile.employment.previous-service.delete',
            'teacher.profile.employment.working-place-history.create',
            'teacher.profile.employment.working-place-history.delete',
            'teacher.profile.employment.position-history.create',
            'teacher.profile.employment.position-history.delete',
            'teacher.profile.pension-and-payment.update',
            'teacher.profile.family.create',
            'teacher.profile.family.delete',
            'principal.list.view',
            'principal.create',
            'principal.profile.general.view',
            'principal.profile.qualification.view',
            'principal.profile.employment.view',
            'principal.profile.family.view',
            'principal.profile.pension-and-payment.view',
            'principal.profile.edit-request.view',
            'principal.profile.edit-request.response',
            'principal.profile.pdf.view',
            'principal.profile.personal-cultural.update',
            'principal.profile.health.update',
            'principal.profile.contact-information.update',
            'principal.profile.location-information.update',
            'principal.profile.temporary-location-information.update',
            'principal.profile.qualification.create',
            'principal.profile.qualification.delete',
            'principal.profile.employment.current-appointment.update',
            'principal.profile.employment.first-appointment.update',
            'principal.profile.employment.principal-information.update',
            'principal.profile.employment.previous-service.create',
            'principal.profile.employment.previous-service.delete',
            'principal.profile.employment.working-place-history.create',
            'principal.profile.employment.working-place-history.delete',
            'principal.profile.pension-and-payment.update',
            'principal.profile.family.create',
            'principal.profile.family.delete',
            'dos.list.view',
            'mso.list.view',
            'sltas.list.view',
            'sltas.create',
            'sltas.profile.general.view',
            'sltas.profile.qualification.view',
            'sltas.profile.employment.view',
            'sltas.profile.family.view',
            'sltas.profile.pension-and-payment.view',
            'sltas.profile.edit-request.view',
            'sltas.profile.edit-request.response',
            'sltas.profile.pdf.view',
            'sltas.profile.personal-cultural.update',
            'sltas.profile.health.update',
            'sltas.profile.contact-information.update',
            'sltas.profile.location-information.update',
            'sltas.profile.temporary-location-information.update',
            'sltas.profile.qualification.create',
            'sltas.profile.qualification.delete',
            'sltas.profile.employment.current-appointment.update',
            'sltas.profile.employment.first-appointment.update',
            'sltas.profile.employment.sltas-information.update',
            'sltas.profile.employment.previous-service.create',
            'sltas.profile.employment.previous-service.delete',
            'sltas.profile.employment.working-place-history.create',
            'sltas.profile.employment.working-place-history.delete',
            'sltas.profile.pension-and-payment.update',
            'sltas.profile.family.create',
            'sltas.profile.family.delete',
            'sltes.list.view',
            'sltes.create',
            'sltes.profile.general.view',
            'sltes.profile.qualification.view',
            'sltes.profile.employment.view',
            'sltes.profile.family.view',
            'sltes.profile.pension-and-payment.view',
            'sltes.profile.edit-request.view',
            'sltes.profile.edit-request.response',
            'sltes.profile.pdf.view',
            'sltes.profile.personal-cultural.update',
            'sltes.profile.health.update',
            'sltes.profile.contact-information.update',
            'sltes.profile.location-information.update',
            'sltes.profile.temporary-location-information.update',
            'sltes.profile.qualification.create',
            'sltes.profile.qualification.delete',
            'sltes.profile.employment.current-appointment.update',
            'sltes.profile.employment.first-appointment.update',
            'sltes.profile.employment.sltes-information.update',
            'sltes.profile.employment.previous-service.create',
            'sltes.profile.employment.previous-service.delete',
            'sltes.profile.employment.working-place-history.create',
            'sltes.profile.employment.working-place-history.delete',
            'sltes.profile.pension-and-payment.update',
            'sltes.profile.family.create',
            'sltes.profile.family.delete',
            'institution.list.view',
            'institution.profile.overview.view',
            'office.zeo.list.view',
            'office.deo.list.view',
            'office.institution.list.view',
            'office.peo.profile.overview.view',
            'office.zeo.profile.overview.view',
            'office.deo.profile.overview.view',
            'office.institution.profile.overview.view',
            'office.institution.profile.profile.view',
            'office.institution.profile.staff.view',
            'office.institution.profile.report-module.view',
            'office.overview',
        ]);

        // Create sltas role and assign specific permissions
        $sltasRole = Role::firstOrCreate(['name' => 'sltas']);
        $sltasRole->syncPermissions([
            'my-profile.general.view',
            'my-profile.qualification.view',
            'my-profile.employment.view',
            'my-profile.family.view',
            'my-profile.pension-and-payment.view',
            'my-profile.edit-request.view',
            'my-profile.edit-request.create',
            'my-profile.pdf.view',
        ]);

        // Create development officer role and assign specific permissions
        $developmentOfficerRole = Role::firstOrCreate(['name' => 'development officer']);
        $developmentOfficerRole->syncPermissions([
            'dashboard.main.view',
            'student.list.view',
            'attendance.list.view',
            'attendance.manage.update',
            'exam.result.view',
            'exam.term_test.manage',
            'resource.list.view',
            'resource.manage.update',
            'resource.allocation.create',
            'resource.allocation.view',
            'my-profile.general.view',
            'my-profile.qualification.view',
            'my-profile.employment.view',
            'my-profile.family.view',
            'my-profile.pension-and-payment.view',
            'my-profile.edit-request.view',
            'my-profile.edit-request.create',
            'my-profile.pdf.view',
        ]);

        // Create management assistant role and assign specific permissions
        $managementAssistantRole = Role::firstOrCreate(['name' => 'management assistant']);
        $managementAssistantRole->syncPermissions([
            'dashboard.main.view',
            'student.list.view',
            'attendance.list.view',
            'attendance.manage.update',
            'exam.result.view',
            'exam.term_test.manage',
            'resource.list.view',
            'resource.manage.update',
            'resource.allocation.create',
            'resource.allocation.view',
            'my-profile.general.view',
            'my-profile.qualification.view',
            'my-profile.employment.view',
            'my-profile.family.view',
            'my-profile.pension-and-payment.view',
            'my-profile.edit-request.view',
            'my-profile.edit-request.create',
            'my-profile.pdf.view',
        ]);

        // Create sleas officer role and assign specific permissions
        $sleasOfficerRole = Role::firstOrCreate(['name' => 'sleas officer']);
        $sleasOfficerRole->syncPermissions([
            'dashboard.main.view',
            'student.list.view',
            'attendance.list.view',
            'attendance.manage.update',
            'exam.result.view',
            'exam.term_test.manage',
            'resource.list.view',
            'resource.manage.update',
            'resource.allocation.create',
            'resource.allocation.view',
            'my-profile.general.view',
            'my-profile.qualification.view',
            'my-profile.employment.view',
            'my-profile.family.view',
            'my-profile.pension-and-payment.view',
            'my-profile.edit-request.view',
            'my-profile.edit-request.create',
            'my-profile.pdf.view',
            'office.moe.profile.overview.view',
            'office.pmoe.profile.overview.view',
            'office.peo.profile.overview.view',
            'office.zeo.profile.overview.view',
            'transfer.portal.view',
            'transfer.policy.view',
            'transfer.policy.manage',
            'transfer.request.view',
            'transfer.board.view',
            'transfer.zeo-request.view',
        ]);

        // Create Teacher Advisor role and assign specific permissions
        $teacherAdvisorRole = Role::firstOrCreate(['name' => 'Teacher Advisor']);
        $teacherAdvisorRole->syncPermissions([
            'dashboard.main.view',
            'student.list.view',
            'attendance.list.view',
            'attendance.manage.update',
            'exam.result.view',
            'exam.term_test.manage',
            'resource.list.view',
            'resource.manage.update',
            'resource.allocation.create',
            'resource.allocation.view',
            'my-profile.general.view',
            'my-profile.qualification.view',
            'my-profile.employment.view',
            'my-profile.family.view',
            'my-profile.pension-and-payment.view',
            'my-profile.edit-request.view',
            'my-profile.edit-request.create',
            'my-profile.pdf.view',
        ]);

        // Create Provincial Data Entry role and assign specific permissions
        $provincialDataEntryRole = Role::firstOrCreate(['name' => 'Provincial Data Entry']);
        $provincialDataEntryRole->syncPermissions([
            'dashboard.main.view',
            'attendance.list.view',
            'attendance.manage.update',
            'exam.result.view',
            'exam.term_test.manage',
            'my-profile.general.view',
            'my-profile.qualification.view',
            'my-profile.employment.view',
            'my-profile.family.view',
            'my-profile.pension-and-payment.view',
            'my-profile.edit-request.view',
            'my-profile.edit-request.create',
            'my-profile.edit-request.response',
            'my-profile.confirm',
            'my-profile.pdf.view',
            'my-profile.employment.first-appointment.update',
            'my-profile.employment.working-place-history.create',
            'dos.list.view',
            'dos.create',
            'dos.update',
            'dos.delete',
            'dos.profile.general.view',
            'dos.profile.qualification.view',
            'dos.profile.employment.view',
            'dos.profile.family.view',
            'dos.profile.pension-and-payment.view',
            'dos.profile.edit-request.view',
            'dos.profile.edit-request.create',
            'dos.profile.edit-request.response',
            'dos.profile.verify',
            'dos.profile.confirm',
            'dos.profile.pdf.view',
            'dos.profile.personal-cultural.update',
            'dos.profile.health.update',
            'dos.profile.contact-information.update',
            'dos.profile.location-information.update',
            'dos.profile.temporary-location-information.update',
            'dos.profile.qualification.create',
            'dos.profile.qualification.delete',
            'dos.profile.employment.current-appointment.update',
            'dos.profile.employment.first-appointment.update',
            'dos.profile.employment.dos-information.update',
            'dos.profile.employment.previous-service.create',
            'dos.profile.employment.previous-service.delete',
            'dos.profile.employment.working-place-history.create',
            'dos.profile.employment.working-place-history.delete',
            'dos.profile.pension-and-payment.update',
            'dos.profile.family.create',
            'dos.profile.family.delete',
            'mso.list.view',
            'mso.create',
            'mso.update',
            'mso.delete',
            'mso.profile.general.view',
            'mso.profile.qualification.view',
            'mso.profile.employment.view',
            'mso.profile.family.view',
            'mso.profile.pension-and-payment.view',
            'mso.profile.edit-request.view',
            'mso.profile.edit-request.create',
            'mso.profile.edit-request.response',
            'mso.profile.verify',
            'mso.profile.confirm',
            'mso.profile.pdf.view',
            'mso.profile.personal-cultural.update',
            'mso.profile.health.update',
            'mso.profile.contact-information.update',
            'mso.profile.location-information.update',
            'mso.profile.temporary-location-information.update',
            'mso.profile.qualification.create',
            'mso.profile.qualification.delete',
            'mso.profile.employment.current-appointment.update',
            'mso.profile.employment.first-appointment.update',
            'mso.profile.employment.mso-information.update',
            'mso.profile.employment.previous-service.create',
            'mso.profile.employment.previous-service.delete',
            'mso.profile.employment.working-place-history.create',
            'mso.profile.employment.working-place-history.delete',
            'mso.profile.pension-and-payment.update',
            'mso.profile.family.create',
            'mso.profile.family.delete',
            'sleas.list.view',
            'sleas.create',
            'sleas.profile.general.view',
            'sleas.profile.qualification.view',
            'sleas.profile.employment.view',
            'sleas.profile.family.view',
            'sleas.profile.pension-and-payment.view',
            'sleas.profile.edit-request.view',
            'sleas.profile.edit-request.create',
            'sleas.profile.edit-request.response',
            'sleas.profile.pdf.view',
            'sleas.profile.personal-cultural.update',
            'sleas.profile.health.update',
            'sleas.profile.contact-information.update',
            'sleas.profile.location-information.update',
            'sleas.profile.temporary-location-information.update',
            'sleas.profile.qualification.create',
            'sleas.profile.qualification.delete',
            'sleas.profile.employment.current-appointment.update',
            'sleas.profile.employment.first-appointment.update',
            'sleas.profile.employment.sleas-information.update',
            'sleas.profile.employment.previous-service.create',
            'sleas.profile.employment.previous-service.delete',
            'sleas.profile.employment.working-place-history.create',
            'sleas.profile.employment.working-place-history.delete',
            'sleas.profile.pension-and-payment.update',
            'sleas.profile.family.create',
            'sleas.profile.family.delete',
            'institution.list.view',
            'institution.create',
            'institution.update',
            'institution.profile.view',
            'institution.profile.overview.view',
            'institution.profile.staff.view',
            'institution.profile.report-module.view',
            'institution.profile.report-module.pdf',
            'institution.profile.report-module.xls',
            'institution.basic_information.update',
            'institution.contact_details.update',
            'institution.location_administration.update',
            'institution.mission_vision.update',
            'appointment_subject.list.view',
            'appointment_subject.create',
            'appointment_subject.update',
            'appointment_subject.delete',
            'appointment_subject.view',
            'office.moe.list.view',
            'office.pmoe.list.view',
            'office.peo.list.view',
            'office.zeo.list.view',
            'office.deo.list.view',
            'office.institution.list.view',
            'office.moe.create',
            'office.pmoe.create',
            'office.peo.create',
            'office.zeo.create',
            'office.deo.create',
            'office.institution.create',
            'office.moe.profile.overview.view',
            'office.pmoe.profile.overview.view',
            'office.peo.profile.overview.view',
            'office.zeo.profile.overview.view',
            'office.deo.profile.overview.view',
            'office.moe.update',
            'office.pmoe.update',
            'office.peo.update',
            'office.zeo.update',
            'office.deo.update',
            'office.institution.update',
            'office.moe.delete',
            'office.pmoe.delete',
            'office.peo.delete',
            'office.zeo.delete',
            'office.deo.delete',
            'office.institution.delete',
            'office.institution.profile.overview.view',
            'office.institution.profile.profile.view',
            'office.institution.profile.staff.view',
            'office.institution.profile.report-module.view',
            'office.institution.profile.report-module.pdf',
            'office.institution.profile.report-module.xls',
            'office.overview',
        ]);

        // Create Zonal Data Verify role and assign specific permissions
        $zonalDataVerifyRole = Role::firstOrCreate(['name' => 'Zonal Data Verify']);
        $zonalDataVerifyRole->syncPermissions([
            'my-profile.general.view',
            'my-profile.qualification.view',
            'my-profile.employment.view',
            'my-profile.family.view',
            'my-profile.pension-and-payment.view',
            'my-profile.edit-request.view',
            'my-profile.pdf.view',
            'teacher.list.view',
            'teacher.profile.general.view',
            'teacher.profile.qualification.view',
            'teacher.profile.employment.view',
            'teacher.profile.family.view',
            'teacher.profile.pension-and-payment.view',
            'teacher.profile.edit-request.view',
            'teacher.profile.verify',
            'teacher.profile.pdf.view',
            'principal.list.view',
            'principal.profile.general.view',
            'principal.profile.qualification.view',
            'principal.profile.employment.view',
            'principal.profile.family.view',
            'principal.profile.pension-and-payment.view',
            'principal.profile.edit-request.view',
            'principal.profile.verify',
            'principal.profile.pdf.view',
            'dos.list.view',
            'dos.profile.general.view',
            'dos.profile.qualification.view',
            'dos.profile.employment.view',
            'dos.profile.family.view',
            'dos.profile.pension-and-payment.view',
            'dos.profile.edit-request.view',
            'dos.profile.verify',
            'dos.profile.pdf.view',
            'mso.list.view',
            'mso.profile.general.view',
            'mso.profile.qualification.view',
            'mso.profile.employment.view',
            'mso.profile.family.view',
            'mso.profile.pension-and-payment.view',
            'mso.profile.edit-request.view',
            'mso.profile.verify',
            'mso.profile.pdf.view',
            'sltas.list.view',
            'sltas.profile.general.view',
            'sltas.profile.qualification.view',
            'sltas.profile.employment.view',
            'sltas.profile.family.view',
            'sltas.profile.pension-and-payment.view',
            'sltas.profile.edit-request.view',
            'sltas.profile.verify',
            'sltas.profile.pdf.view',
            'sltes.list.view',
            'sltes.profile.general.view',
            'sltes.profile.qualification.view',
            'sltes.profile.employment.view',
            'sltes.profile.family.view',
            'sltes.profile.pension-and-payment.view',
            'sltes.profile.edit-request.view',
            'sltes.profile.verify',
            'sltes.profile.pdf.view',
            'institution.list.view',
            'institution.profile.view',
            'institution.profile.overview.view',
            'institution.profile.staff.view',
            'institution.profile.report-module.view',
            'institution.profile.report-module.pdf',
            'office.zeo.list.view',
            'office.deo.list.view',
            'office.institution.list.view',
            'office.zeo.profile.overview.view',
            'office.deo.profile.overview.view',
            'office.institution.profile.overview.view',
            'office.institution.profile.profile.view',
            'office.institution.profile.staff.view',
            'office.institution.profile.report-module.view',
        ]);

        // Create Zonal Data Confirm role and assign specific permissions
        $zonalDataConfirmRole = Role::firstOrCreate(['name' => 'Zonal Data Confirm']);
        $zonalDataConfirmRole->syncPermissions([
            'teacher.list.view',
            'teacher.profile.general.view',
            'teacher.profile.qualification.view',
            'teacher.profile.employment.view',
            'teacher.profile.family.view',
            'teacher.profile.pension-and-payment.view',
            'teacher.profile.edit-request.view',
            'teacher.profile.confirm',
            'teacher.profile.pdf.view',
            'principal.list.view',
            'principal.profile.general.view',
            'principal.profile.qualification.view',
            'principal.profile.employment.view',
            'principal.profile.family.view',
            'principal.profile.pension-and-payment.view',
            'principal.profile.edit-request.view',
            'principal.profile.confirm',
            'principal.profile.pdf.view',
            'dos.list.view',
            'dos.profile.general.view',
            'dos.profile.qualification.view',
            'dos.profile.employment.view',
            'dos.profile.family.view',
            'dos.profile.pension-and-payment.view',
            'dos.profile.edit-request.view',
            'dos.profile.confirm',
            'dos.profile.pdf.view',
            'mso.list.view',
            'mso.profile.general.view',
            'mso.profile.qualification.view',
            'mso.profile.employment.view',
            'mso.profile.family.view',
            'mso.profile.pension-and-payment.view',
            'mso.profile.edit-request.view',
            'mso.profile.confirm',
            'mso.profile.pdf.view',
            'sltas.list.view',
            'sltas.profile.general.view',
            'sltas.profile.qualification.view',
            'sltas.profile.employment.view',
            'sltas.profile.family.view',
            'sltas.profile.pension-and-payment.view',
            'sltas.profile.edit-request.view',
            'sltas.profile.confirm',
            'sltas.profile.pdf.view',
            'sltes.list.view',
            'sltes.profile.general.view',
            'sltes.profile.qualification.view',
            'sltes.profile.employment.view',
            'sltes.profile.family.view',
            'sltes.profile.pension-and-payment.view',
            'sltes.profile.edit-request.view',
            'sltes.profile.confirm',
            'sltes.profile.pdf.view',
            'institution.list.view',
            'institution.profile.view',
            'institution.profile.overview.view',
            'institution.profile.staff.view',
            'institution.profile.report-module.view',
            'institution.profile.report-module.pdf',
            'office.zeo.list.view',
            'office.deo.list.view',
            'office.institution.list.view',
            'office.zeo.profile.overview.view',
            'office.deo.profile.overview.view',
            'office.institution.profile.overview.view',
            'office.institution.profile.profile.view',
            'office.institution.profile.staff.view',
            'office.institution.profile.report-module.view',
        ]);

        // Create Provincial System Admin role and assign specific permissions
        $provincialSystemAdminRole = Role::firstOrCreate(['name' => 'Provincial System Admin']);
        $provincialSystemAdminRole->syncPermissions([
            'dashboard.main.view',
            'my-profile.general.view',
            'my-profile.qualification.view',
            'my-profile.employment.view',
            'my-profile.family.view',
            'my-profile.pension-and-payment.view',
            'my-profile.edit-request.view',
            'my-profile.edit-request.create',
            'my-profile.pdf.view',
            'teacher.list.view',
            'teacher.profile.general.view',
            'teacher.profile.qualification.view',
            'teacher.profile.employment.view',
            'teacher.profile.family.view',
            'teacher.profile.pension-and-payment.view',
            'teacher.profile.edit-request.view',
            'teacher.profile.pdf.view',
            'teacher.profile.employment.current-appointment.update',
            'principal.list.view',
            'principal.profile.general.view',
            'dos.list.view',
            'dos.create',
            'dos.update',
            'dos.delete',
            'dos.profile.general.view',
            'dos.profile.qualification.view',
            'dos.profile.employment.view',
            'dos.profile.family.view',
            'dos.profile.pension-and-payment.view',
            'dos.profile.edit-request.view',
            'dos.profile.edit-request.create',
            'dos.profile.edit-request.response',
            'dos.profile.verify',
            'dos.profile.confirm',
            'dos.profile.pdf.view',
            'dos.profile.personal-cultural.update',
            'dos.profile.health.update',
            'dos.profile.contact-information.update',
            'dos.profile.location-information.update',
            'dos.profile.temporary-location-information.update',
            'dos.profile.qualification.create',
            'dos.profile.qualification.delete',
            'dos.profile.employment.current-appointment.update',
            'dos.profile.employment.first-appointment.update',
            'dos.profile.employment.dos-information.update',
            'dos.profile.employment.previous-service.create',
            'dos.profile.employment.previous-service.delete',
            'dos.profile.employment.working-place-history.create',
            'dos.profile.employment.working-place-history.delete',
            'dos.profile.pension-and-payment.update',
            'dos.profile.family.create',
            'dos.profile.family.delete',
            'mso.list.view',
            'mso.create',
            'mso.update',
            'mso.delete',
            'mso.profile.general.view',
            'mso.profile.qualification.view',
            'mso.profile.employment.view',
            'mso.profile.family.view',
            'mso.profile.pension-and-payment.view',
            'mso.profile.edit-request.view',
            'mso.profile.edit-request.create',
            'mso.profile.edit-request.response',
            'mso.profile.verify',
            'mso.profile.confirm',
            'mso.profile.pdf.view',
            'mso.profile.personal-cultural.update',
            'mso.profile.health.update',
            'mso.profile.contact-information.update',
            'mso.profile.location-information.update',
            'mso.profile.temporary-location-information.update',
            'mso.profile.qualification.create',
            'mso.profile.qualification.delete',
            'mso.profile.employment.current-appointment.update',
            'mso.profile.employment.first-appointment.update',
            'mso.profile.employment.mso-information.update',
            'mso.profile.employment.previous-service.create',
            'mso.profile.employment.previous-service.delete',
            'mso.profile.employment.working-place-history.create',
            'mso.profile.employment.working-place-history.delete',
            'mso.profile.pension-and-payment.update',
            'mso.profile.family.create',
            'mso.profile.family.delete',
            'sleas.list.view',
            'sleas.create',
            'sleas.update',
            'sleas.delete',
            'sleas.profile.general.view',
            'sleas.profile.qualification.view',
            'sleas.profile.employment.view',
            'sleas.profile.family.view',
            'sleas.profile.pension-and-payment.view',
            'sleas.profile.edit-request.view',
            'sleas.profile.edit-request.create',
            'sleas.profile.edit-request.response',
            'sleas.profile.verify',
            'sleas.profile.confirm',
            'sleas.profile.pdf.view',
            'sleas.profile.personal-cultural.update',
            'sleas.profile.health.update',
            'sleas.profile.contact-information.update',
            'sleas.profile.location-information.update',
            'sleas.profile.temporary-location-information.update',
            'sleas.profile.qualification.create',
            'sleas.profile.qualification.delete',
            'sleas.profile.employment.current-appointment.update',
            'sleas.profile.employment.first-appointment.update',
            'sleas.profile.employment.sleas-information.update',
            'sleas.profile.employment.previous-service.create',
            'sleas.profile.employment.previous-service.delete',
            'sleas.profile.employment.working-place-history.create',
            'sleas.profile.employment.working-place-history.delete',
            'sleas.profile.pension-and-payment.update',
            'sleas.profile.family.create',
            'sleas.profile.family.delete',
            'user.list.view',
            'user.password.reset',
            'institution.list.view',
            'institution.create',
            'institution.update',
            'institution.profile.view',
            'institution.profile.overview.view',
            'institution.profile.staff.view',
            'institution.profile.report-module.view',
            'institution.profile.report-module.pdf',
            'institution.profile.report-module.xls',
            'institution.basic_information.update',
            'institution.contact_details.update',
            'institution.location_administration.update',
            'institution.mission_vision.update',
            'office.pmoe.list.view',
            'office.peo.list.view',
            'office.zeo.list.view',
            'office.deo.list.view',
            'office.institution.list.view',
            'office.institution.create',
            'office.pmoe.profile.overview.view',
            'office.peo.profile.overview.view',
            'office.zeo.profile.overview.view',
            'office.deo.profile.overview.view',
            'office.peo.update',
            'office.institution.update',
            'office.institution.profile.overview.view',
            'office.institution.profile.profile.view',
            'office.institution.profile.staff.view',
            'office.institution.profile.report-module.view',
            'office.institution.profile.report-module.pdf',
            'office.institution.profile.report-module.xls',
            'cadre-dms-approved.index.view',
            'cadre-dms-approved.add',
            'cadre-dms-approved.institution.view',
            'cadre-dms-approved.edit',
            'institution.profile.cadre-dms-approved.view',
            'office.institution.profile.cadre-dms-approved.view',
            'employee.profile.create.any',
            'employee.overview.view',
            'office.overview',
        ]);

        // Create Zonal System Admin role and assign specific permissions
        $zonalSystemAdminRole = Role::firstOrCreate(['name' => 'Zonal System Admin']);
        $zonalSystemAdminRole->syncPermissions([
            'dashboard.main.view',
            'my-profile.general.view',
            'my-profile.qualification.view',
            'my-profile.employment.view',
            'my-profile.family.view',
            'my-profile.pension-and-payment.view',
            'my-profile.edit-request.view',
            'my-profile.edit-request.create',
            'my-profile.pdf.view',
            'teacher.list.view',
            'teacher.profile.general.view',
            'teacher.profile.qualification.view',
            'teacher.profile.employment.view',
            'teacher.profile.family.view',
            'teacher.profile.pension-and-payment.view',
            'teacher.profile.edit-request.view',
            'teacher.profile.confirm',
            'teacher.profile.pdf.view',
            'principal.list.view',
            'principal.create',
            'principal.update',
            'principal.delete',
            'principal.profile.general.view',
            'principal.profile.qualification.view',
            'principal.profile.employment.view',
            'principal.profile.family.view',
            'principal.profile.pension-and-payment.view',
            'principal.profile.edit-request.view',
            'principal.profile.edit-request.create',
            'principal.profile.edit-request.response',
            'principal.profile.confirm',
            'principal.profile.pdf.view',
            'principal.profile.personal-cultural.update',
            'principal.profile.health.update',
            'principal.profile.contact-information.update',
            'principal.profile.location-information.update',
            'principal.profile.temporary-location-information.update',
            'principal.profile.qualification.create',
            'principal.profile.qualification.delete',
            'principal.profile.employment.current-appointment.update',
            'principal.profile.employment.first-appointment.update',
            'principal.profile.employment.principal-information.update',
            'principal.profile.employment.previous-service.create',
            'principal.profile.employment.previous-service.delete',
            'principal.profile.employment.working-place-history.create',
            'principal.profile.employment.working-place-history.delete',
            'principal.profile.pension-and-payment.update',
            'principal.profile.family.create',
            'principal.profile.family.delete',
            'dos.list.view',
            'dos.create',
            'dos.update',
            'dos.delete',
            'dos.profile.general.view',
            'dos.profile.qualification.view',
            'dos.profile.employment.view',
            'dos.profile.family.view',
            'dos.profile.pension-and-payment.view',
            'dos.profile.edit-request.view',
            'dos.profile.edit-request.create',
            'dos.profile.edit-request.response',
            'dos.profile.confirm',
            'dos.profile.pdf.view',
            'dos.profile.personal-cultural.update',
            'dos.profile.health.update',
            'dos.profile.contact-information.update',
            'dos.profile.location-information.update',
            'dos.profile.temporary-location-information.update',
            'dos.profile.qualification.create',
            'dos.profile.qualification.delete',
            'dos.profile.employment.current-appointment.update',
            'dos.profile.employment.first-appointment.update',
            'dos.profile.employment.dos-information.update',
            'dos.profile.employment.previous-service.create',
            'dos.profile.employment.previous-service.delete',
            'dos.profile.employment.working-place-history.create',
            'dos.profile.employment.working-place-history.delete',
            'dos.profile.pension-and-payment.update',
            'dos.profile.family.create',
            'dos.profile.family.delete',
            'mso.list.view',
            'mso.create',
            'mso.update',
            'mso.delete',
            'mso.profile.general.view',
            'mso.profile.qualification.view',
            'mso.profile.employment.view',
            'mso.profile.family.view',
            'mso.profile.pension-and-payment.view',
            'mso.profile.edit-request.view',
            'mso.profile.edit-request.create',
            'mso.profile.edit-request.response',
            'mso.profile.confirm',
            'mso.profile.pdf.view',
            'mso.profile.personal-cultural.update',
            'mso.profile.health.update',
            'mso.profile.contact-information.update',
            'mso.profile.location-information.update',
            'mso.profile.temporary-location-information.update',
            'mso.profile.qualification.create',
            'mso.profile.qualification.delete',
            'mso.profile.employment.current-appointment.update',
            'mso.profile.employment.first-appointment.update',
            'mso.profile.employment.mso-information.update',
            'mso.profile.employment.previous-service.create',
            'mso.profile.employment.previous-service.delete',
            'mso.profile.employment.working-place-history.create',
            'mso.profile.employment.working-place-history.delete',
            'mso.profile.pension-and-payment.update',
            'mso.profile.family.create',
            'mso.profile.family.delete',
            'sleas.list.view',
            'sleas.create',
            'sleas.update',
            'sleas.profile.general.view',
            'sleas.profile.qualification.view',
            'sleas.profile.employment.view',
            'sleas.profile.family.view',
            'sleas.profile.pension-and-payment.view',
            'sleas.profile.edit-request.view',
            'sleas.profile.pdf.view',
            'sleas.profile.personal-cultural.update',
            'sleas.profile.health.update',
            'sleas.profile.location-information.update',
            'sleas.profile.temporary-location-information.update',
            'sleas.profile.qualification.create',
            'sleas.profile.qualification.delete',
            'sleas.profile.employment.current-appointment.update',
            'sleas.profile.employment.first-appointment.update',
            'sleas.profile.employment.sleas-information.update',
            'sleas.profile.employment.previous-service.create',
            'sleas.profile.employment.previous-service.delete',
            'sleas.profile.employment.working-place-history.create',
            'sleas.profile.employment.working-place-history.delete',
            'sleas.profile.pension-and-payment.update',
            'sleas.profile.family.create',
            'sleas.profile.family.delete',
            'sltas.list.view',
            'sltas.create',
            'sltas.delete',
            'sltas.profile.confirm',
            'sltes.list.view',
            'sltes.create',
            'sltes.delete',
            'sltes.profile.confirm',
            'institution.list.view',
            'institution.profile.overview.view',
            'office.zeo.list.view',
            'office.deo.list.view',
            'office.institution.list.view',
            'office.zeo.profile.overview.view',
            'office.deo.profile.overview.view',
            'office.institution.update',
            'office.institution.profile.overview.view',
            'office.institution.profile.profile.view',
            'office.institution.profile.staff.view',
            'office.institution.profile.report-module.view',
            'office.institution.profile.report-module.pdf',
            'office.institution.profile.report-module.xls',
            'cadre-dms-approved.index.view',
            'cadre-dms-approved.add',
            'cadre-dms-approved.institution.view',
            'cadre-dms-approved.edit',
            'institution.profile.cadre-dms-approved.view',
            'office.institution.profile.cadre-dms-approved.view',
            'teacher.overview.view',
            'employee.profile.create.any',
            'office.hierarchy.view',
            'transfer.portal.view',
            'transfer.policy.view',
            'transfer.request.view',
            'transfer.board.view',
            'transfer.institution-request.view',
            'transfer.zeo-request.view',
            'employee.overview.view',
            'institution-group.index.view',
            'institution-group.institution-list.view',
            'institution-group.principal-list.view',
            'institution-group.teacher-list.view',
            'office.overview',
            'transfer.annual.view',
            'transfer.mutual.view',
            'transfer.special.view',
        ]);

        // Create Zonal Admin Data Entry role and assign specific permissions
        $zonalAdminDataEntryRole = Role::firstOrCreate(['name' => 'Zonal Admin Data Entry']);
        $zonalAdminDataEntryRole->syncPermissions([
            'teacher.list.view',
            'teacher.profile.general.view',
            'principal.list.view',
            'principal.profile.general.view',
            'dos.list.view',
            'dos.create',
            'dos.profile.general.view',
            'dos.profile.qualification.view',
            'dos.profile.employment.view',
            'dos.profile.family.view',
            'dos.profile.pension-and-payment.view',
            'dos.profile.pdf.view',
            'dos.profile.personal-cultural.update',
            'dos.profile.health.update',
            'dos.profile.contact-information.update',
            'dos.profile.location-information.update',
            'dos.profile.temporary-location-information.update',
            'dos.profile.qualification.create',
            'dos.profile.qualification.delete',
            'dos.profile.employment.current-appointment.update',
            'dos.profile.employment.first-appointment.update',
            'dos.profile.employment.dos-information.update',
            'dos.profile.employment.previous-service.create',
            'dos.profile.employment.previous-service.delete',
            'dos.profile.employment.working-place-history.create',
            'dos.profile.employment.working-place-history.delete',
            'dos.profile.pension-and-payment.update',
            'dos.profile.family.create',
            'dos.profile.family.delete',
            'mso.list.view',
            'mso.create',
            'mso.profile.general.view',
            'mso.profile.qualification.view',
            'mso.profile.employment.view',
            'mso.profile.family.view',
            'mso.profile.pension-and-payment.view',
            'mso.profile.edit-request.view',
            'mso.profile.pdf.view',
            'mso.profile.personal-cultural.update',
            'mso.profile.health.update',
            'mso.profile.contact-information.update',
            'mso.profile.location-information.update',
            'mso.profile.temporary-location-information.update',
            'mso.profile.qualification.create',
            'mso.profile.qualification.delete',
            'mso.profile.employment.current-appointment.update',
            'mso.profile.employment.first-appointment.update',
            'mso.profile.employment.mso-information.update',
            'mso.profile.employment.previous-service.create',
            'mso.profile.employment.previous-service.delete',
            'mso.profile.employment.working-place-history.create',
            'mso.profile.employment.working-place-history.delete',
            'mso.profile.pension-and-payment.update',
            'mso.profile.family.create',
            'mso.profile.family.delete',
            'sleas.list.view',
            'sleas.create',
            'sleas.update',
            'sleas.profile.general.view',
            'sleas.profile.qualification.view',
            'sleas.profile.employment.view',
            'sleas.profile.family.view',
            'sleas.profile.pension-and-payment.view',
            'sleas.profile.edit-request.view',
            'sleas.profile.pdf.view',
            'sleas.profile.personal-cultural.update',
            'sleas.profile.health.update',
            'sleas.profile.contact-information.update',
            'sleas.profile.location-information.update',
            'sleas.profile.temporary-location-information.update',
            'sleas.profile.qualification.create',
            'sleas.profile.qualification.delete',
            'sleas.profile.employment.current-appointment.update',
            'sleas.profile.employment.first-appointment.update',
            'sleas.profile.employment.sleas-information.update',
            'sleas.profile.employment.previous-service.create',
            'sleas.profile.employment.previous-service.delete',
            'sleas.profile.employment.working-place-history.create',
            'sleas.profile.employment.working-place-history.delete',
            'sleas.profile.pension-and-payment.update',
            'sleas.profile.family.create',
            'sleas.profile.family.delete',
            'sltas.list.view',
            'sltas.profile.general.view',
            'sltes.list.view',
            'sltes.profile.general.view',
            'institution.list.view',
            'institution.profile.view',
            'institution.profile.overview.view',
            'institution.profile.staff.view',
            'office.zeo.list.view',
            'office.deo.list.view',
            'office.institution.list.view',
            'office.zeo.profile.overview.view',
            'office.institution.profile.overview.view',
            'office.institution.profile.profile.view',
            'office.institution.profile.staff.view',
            'office.institution.profile.report-module.view',
        ]);

        // Create MOE View Only role and assign specific permissions
        $mOEViewOnlyRole = Role::firstOrCreate(['name' => 'MOE View Only']);
        $mOEViewOnlyRole->syncPermissions([
            'my-profile.general.view',
            'my-profile.qualification.view',
            'my-profile.employment.view',
            'my-profile.family.view',
            'my-profile.pension-and-payment.view',
            'my-profile.edit-request.view',
            'my-profile.pdf.view',
            'teacher.list.view',
            'teacher.profile.general.view',
            'teacher.profile.qualification.view',
            'teacher.profile.employment.view',
            'teacher.profile.family.view',
            'teacher.profile.pension-and-payment.view',
            'teacher.profile.edit-request.view',
            'teacher.profile.pdf.view',
            'principal.list.view',
            'principal.profile.general.view',
            'principal.profile.qualification.view',
            'principal.profile.employment.view',
            'principal.profile.family.view',
            'principal.profile.pension-and-payment.view',
            'principal.profile.edit-request.view',
            'principal.profile.pdf.view',
            'sltas.list.view',
            'sltas.create',
            'sltas.update',
            'sltas.profile.general.view',
            'sltas.profile.qualification.view',
            'sltas.profile.employment.view',
            'sltas.profile.family.view',
            'sltas.profile.pension-and-payment.view',
            'sltas.profile.edit-request.view',
            'sltas.profile.pdf.view',
            'sltas.profile.personal-cultural.update',
            'sltas.profile.health.update',
            'sltas.profile.contact-information.update',
            'sltas.profile.location-information.update',
            'sltas.profile.temporary-location-information.update',
            'sltas.profile.qualification.create',
            'sltas.profile.qualification.delete',
            'sltas.profile.employment.current-appointment.update',
            'sltas.profile.employment.first-appointment.update',
            'sltas.profile.employment.sltas-information.update',
            'sltas.profile.employment.previous-service.create',
            'sltas.profile.employment.previous-service.delete',
            'sltas.profile.employment.working-place-history.create',
            'sltas.profile.employment.working-place-history.delete',
            'sltas.profile.pension-and-payment.update',
            'sltas.profile.family.create',
            'sltas.profile.family.delete',
            'institution.list.view',
            'institution.profile.view',
            'institution.profile.overview.view',
            'institution.profile.staff.view',
            'office.moe.list.view',
            'office.pmoe.list.view',
            'office.peo.list.view',
            'office.zeo.list.view',
            'office.deo.list.view',
            'office.institution.list.view',
            'office.moe.profile.overview.view',
            'office.pmoe.profile.overview.view',
            'office.peo.profile.overview.view',
            'office.zeo.profile.overview.view',
            'office.deo.profile.overview.view',
            'office.institution.profile.overview.view',
            'office.institution.profile.profile.view',
            'office.institution.profile.staff.view',
            'office.institution.profile.report-module.view',
        ]);

        // Create cadre data entry role and assign specific permissions
        $cadreDataEntryRole = Role::firstOrCreate(['name' => 'cadre data entry']);
        $cadreDataEntryRole->syncPermissions([
            'institution.list.view',
            'institution.profile.view',
            'institution.profile.overview.view',
            'institution.profile.staff.view',
            'office.zeo.list.view',
            'office.deo.list.view',
            'office.institution.list.view',
            'office.zeo.profile.overview.view',
            'office.deo.profile.overview.view',
            'office.institution.profile.overview.view',
            'office.institution.profile.profile.view',
            'office.institution.profile.staff.view',
            'office.institution.profile.report-module.view',
            'cadre-dms-approved.index.view',
            'cadre-dms-approved.add',
            'cadre-dms-approved.institution.view',
            'cadre-dms-approved.edit',
            'institution.profile.cadre-dms-approved.view',
            'office.institution.profile.cadre-dms-approved.view',
        ]);

        // Create Administrative Service role and assign specific permissions
        $administrativeServiceRole = Role::firstOrCreate(['name' => 'Administrative Service']);
        $administrativeServiceRole->syncPermissions([
            'dashboard.main.view',
            'student.list.view',
            'attendance.list.view',
            'attendance.manage.update',
            'exam.result.view',
            'exam.term_test.manage',
            'resource.list.view',
            'resource.manage.update',
            'resource.allocation.create',
            'resource.allocation.view',
            'my-profile.general.view',
            'my-profile.qualification.view',
            'my-profile.employment.view',
            'my-profile.family.view',
            'my-profile.pension-and-payment.view',
            'my-profile.edit-request.view',
            'my-profile.edit-request.create',
            'my-profile.pdf.view',
            'office.moe.profile.overview.view',
            'office.pmoe.profile.overview.view',
            'office.peo.profile.overview.view',
            'office.zeo.profile.overview.view',
            'transfer.portal.view',
            'transfer.policy.view',
            'transfer.policy.manage',
            'transfer.request.view',
            'transfer.board.view',
            'transfer.zeo-request.view',
        ]);

        // Create Accountancy Service role and assign specific permissions
        $accountancyServiceRole = Role::firstOrCreate(['name' => 'Accountancy Service']);
        $accountancyServiceRole->syncPermissions([
            'dashboard.main.view',
            'student.list.view',
            'attendance.list.view',
            'attendance.manage.update',
            'exam.result.view',
            'exam.term_test.manage',
            'resource.list.view',
            'resource.manage.update',
            'resource.allocation.create',
            'resource.allocation.view',
            'my-profile.general.view',
            'my-profile.qualification.view',
            'my-profile.employment.view',
            'my-profile.family.view',
            'my-profile.pension-and-payment.view',
            'my-profile.edit-request.view',
            'my-profile.edit-request.create',
            'my-profile.pdf.view',
        ]);

        // Create Teacher Educator role and assign specific permissions
        $teacherEducatorRole = Role::firstOrCreate(['name' => 'Teacher Educator']);
        $teacherEducatorRole->syncPermissions([
            'dashboard.main.view',
            'student.list.view',
            'attendance.list.view',
            'attendance.manage.update',
            'exam.result.view',
            'exam.term_test.manage',
            'resource.list.view',
            'resource.manage.update',
            'resource.allocation.create',
            'resource.allocation.view',
            'my-profile.general.view',
            'my-profile.qualification.view',
            'my-profile.employment.view',
            'my-profile.family.view',
            'my-profile.pension-and-payment.view',
            'my-profile.edit-request.view',
            'my-profile.edit-request.create',
            'my-profile.pdf.view',
        ]);


        // Create School System Admin role and assign specific permissions
        $schoolSystemAdminRole = Role::firstOrCreate(['name' => 'School System Admin']);
        $schoolSystemAdminRole->syncPermissions([
            "dashboard.main.view",
            "student.list.view",
            "attendance.list.view",
            "attendance.manage.update",
            "exam.result.view",
            "exam.term_test.manage",
            "resource.list.view",
            "resource.manage.update",
            "resource.allocation.create",
            "resource.allocation.view",
            "my-profile.general.view",
            "my-profile.qualification.view",
            "my-profile.employment.view",
            "my-profile.family.view",
            "my-profile.pension-and-payment.view",
            "my-profile.edit-request.view",
            "my-profile.edit-request.create",
            "my-profile.pdf.view",
            "user.list.view",
            "user.password.reset",
            "institution.list.view",
            "institution.profile.view",
            "institution.profile.overview.view",
            "institution.profile.staff.view",
            "institution.profile.report-module.view",
            "institution.profile.report-module.pdf",
            "office.institution.list.view",
            "office.institution.profile.overview.view",
            "office.institution.profile.profile.view",
            "office.institution.profile.staff.view",
            "office.institution.profile.report-module.view",
            "office.institution.profile.report-module.pdf",
            "office.institution.profile.report-module.xls",
            "office.institution.profile.cadre-dms-approved.view",
            "institution.profile.profile.view",
            "office.hierarchy.view",
            "transfer.institution-request.view",
            "employee.overview.view",
            "office.overview",
            "employee.mytransfer"
        ]);

        // Any role that can enter the dashboard should be able to open its own
        // profile from the dashboard and sidebar without hitting a 403.
        Role::whereHas('permissions', function ($query) {
            $query->where('name', 'dashboard.main.view');
        })->get()->each(function (Role $role) use ($selfProfilePermissions) {
            $role->givePermissionTo($selfProfilePermissions);
        });
    }
}
